[package]
name = "ParticleSim"
version = "0.1.5"
edition = "2021"

[dependencies]
quarkstrom = { git = "https://github.com/DeadlockCode/quarkstrom", rev = "8aa27dba1739f09b4d1372faa8553e64a3f0549d" }

ultraviolet = { version = "0.9.2", features = ["serde"] }
fastrand = "2.1.1"
broccoli = "6.3.0"
palette = "0.7.6"

parking_lot = "0.12.3"
once_cell = "1.20.1"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

rayon = "1.10.0"
crossbeam = "0.8.4"
broccoli-rayon = "0.4.0"
rand = "0.9.1"
smallvec = "1.10.0"

[features]
profiling = []
debug_quadtree = []
