name = "five"
interval_fs = 1000.0
output_file = "manual_measurements.csv"

[[points]]
x = 0.0
y = -150.0
height = 50.0
width = 70.0
direction = "left"
label = "Foil3_Y-180"

[[points]]
x = 0.0
y = -80.0
height = 50.0
width = 70.0
direction = "left"
label = "Foil3_Y-90"

[[points]]
x = 0.0
y = 0.0
height = 50.0
width = 70.0
direction = "left"
label = "Foil3_Y0"

[[points]]
x = 0.0
y = 80.0
height = 50.0
width = 70.0
direction = "left"
label = "Foil3_Y+90"

[[points]]
x = 0.0
y = 150.0
height = 50.0
width = 70.0
direction = "left"
label = "Foil3_Y+180"
